# Generated by Django 2.1.15 on 2020-02-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='time_minues',
            new_name='time_minutes',
        ),
    ]
